version: '3.9'
services:
  dev-finder-db:
    image: postgres
    restart: always
    container_name: dev-finder-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
# Define What container you want to spin up when you run docker compose up
# I need you to spin up Postgres DB on port 5432
# volumes telling docker to grab some place in my disk to bind to the container, so it can actually persist data as you are working
